version: '3.3'

services:
   node:
     links:
       - api
     build: .
     stdin_open: true
     environment:
       - NODE_ENV=production
     volumes:
       - ./wpreact-app:/home/
     ports:
       - "3000:3000"

   db:
     image: mysql:5.7
     volumes:
       - dbdata:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   api:
     depends_on:
       - db
     image: wordpress 
     volumes:
       - ./wpreact-theme:/var/www/html/wp-content/themes/wpreact
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
volumes:
    dbdata: